# Beyond Static Models: Evaluating Drift-Aware Retraining for Time-Series Anomaly Detection
# Starling 🌟
***Starling is a time-series anomaly detection research project. Its goal is to investigate how different retraining strategies affect anomaly detection when time-series data changes over time.***

## Description
This file has been made to do some researches on data and also get some valuable informations from it. <br>
The Repo explores NASA-SMAP/MSL data for Anomaly Detection.

### Dependencies

In [2]:
import numpy as np
from dotenv import load_dotenv
import os
from pathlib import Path
import pandas as pd
load_dotenv()

True

### Data Exploration -> Load

In [ ]:
train_data_dir = os.getenv("train_data_dir")
for file_path in Path(train_data_dir).rglob("*.npy"):
    data = np.load(file_path,mmap_mode="r")
    # print(f"\nFile name: {file_path.name}")
    # print(f'data shape: {data.shape}')
    # print('==============================')
    # print(f'data type: {data.dtype}')
    # print('==============================')
    # print(f'First values: ')
    # print(data[:5])

In [6]:
meta_data = pd.read_csv(os.getenv('meta_data'))
print("Spacecraft counts:")
print(meta_data["spacecraft"].value_counts())

print("\nChannels per spacecraft:")
print(
    meta_data.groupby("spacecraft")["chan_id"]
    .agg(["count", "nunique"])
)

print("\nExample channels:")
display(
    meta_data[["chan_id", "spacecraft", "class", "num_values"]]
    
)



duplicates = meta_data[
    meta_data["chan_id"].duplicated(keep=False)
].sort_values("chan_id")

display(duplicates)

Spacecraft counts:
spacecraft
SMAP    55
MSL     27
Name: count, dtype: int64

Channels per spacecraft:
            count  nunique
spacecraft
MSL            27       27
SMAP           55       54

Example channels:

   chan_id spacecraft                                 class  num_values
0      P-1       SMAP  [contextual, contextual, contextual]        8505
1      S-1       SMAP                               [point]        7331
2      E-1       SMAP              [contextual, contextual]        8516
3      E-2       SMAP                               [point]        8532
4      E-3       SMAP                               [point]        8307
..     ...        ...                                   ...         ...
77    P-11        MSL                        [point, point]        3535
78    D-15        MSL                               [point]        2158
79    D-16        MSL                          [contextual]        2191
80     M-7        MSL                               [point]        2156
81     F-8        MSL                          [contextual]        2487

[82 rows x 4 columns]

   chan_id spacecraft anomaly_sequences    class  num_values
17     P-2       SMAP    [[5350, 6575]]  [point]        8209
51     P-2       SMAP    [[5300, 6420]]  [point]        8209